language: rust
sudo: false
dist: xenial

cache:
  cargo: true
  apt: true

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
  allow_failures:
    - rust: stable
    - rust: beta

# Add clippy
before_script:
  - export PATH=$PATH:~/.cargo/bin

script:
  - |
    cargo clean
    cargo test -- --nocapture
